### ISSUE TITLE
image property missing from JSON

### ISSUE THREAD

**Issue by anurodhp** [dave-p/TVH-API-docs#2]
The Api description for the entry under /api/epg/events/grid is missing the image property which contains a string with a URL to an image related to the program

**Comment by dave-p** [comment]
Do you mean that the example output from epg/events/grid is missing that item? The example was taken from the local off-air EPG which does not include images so that item is not shown.
I've updated the text to explain that there are many more possible properties which may be shown if the EPG provider makes the information available.
